CREATE TABLE IF NOT EXISTS public.workload_batch
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL,
    teacher_id BIGINT NULL,
    group_name VARCHAR(255) NULL,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_workload_batch_program FOREIGN KEY (program_id) REFERENCES public.learning_program(id) ON DELETE RESTRICT,
    CONSTRAINT fk_workload_batch_teacher FOREIGN KEY (teacher_id) REFERENCES public.teacher(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_workload_batch_program_id ON public.workload_batch(program_id);
CREATE INDEX IF NOT EXISTS ix_workload_batch_teacher_id ON public.workload_batch(teacher_id);

CREATE TABLE IF NOT EXISTS public.workload_document
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL,
    batch_id BIGINT NULL,
    contract_id BIGINT NULL,
    listener_id BIGINT NULL,
    teacher_id BIGINT NULL,
    program_type VARCHAR(255) NULL,
    group_name VARCHAR(255) NULL,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    file_name VARCHAR(500) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    generated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_workload_document_program FOREIGN KEY (program_id) REFERENCES public.learning_program(id) ON DELETE RESTRICT,
    CONSTRAINT fk_workload_document_batch FOREIGN KEY (batch_id) REFERENCES public.workload_batch(id) ON DELETE SET NULL,
    CONSTRAINT fk_workload_document_contract FOREIGN KEY (contract_id) REFERENCES public.contract(id) ON DELETE SET NULL,
    CONSTRAINT fk_workload_document_listener FOREIGN KEY (listener_id) REFERENCES public.person(id) ON DELETE SET NULL,
    CONSTRAINT fk_workload_document_teacher FOREIGN KEY (teacher_id) REFERENCES public.teacher(id) ON DELETE SET NULL
);

ALTER TABLE public.workload_document ADD COLUMN IF NOT EXISTS batch_id BIGINT NULL;
ALTER TABLE public.workload_document ADD COLUMN IF NOT EXISTS contract_id BIGINT NULL;
ALTER TABLE public.workload_document ADD COLUMN IF NOT EXISTS listener_id BIGINT NULL;
ALTER TABLE public.workload_document ADD COLUMN IF NOT EXISTS group_name VARCHAR(255) NULL;
ALTER TABLE public.workload_document ADD COLUMN IF NOT EXISTS is_group BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS ix_workload_document_program_id ON public.workload_document(program_id);
CREATE INDEX IF NOT EXISTS ix_workload_document_teacher_id ON public.workload_document(teacher_id);
CREATE INDEX IF NOT EXISTS ix_workload_document_batch_id ON public.workload_document(batch_id);
CREATE INDEX IF NOT EXISTS ix_workload_document_contract_id ON public.workload_document(contract_id);
CREATE INDEX IF NOT EXISTS ix_workload_document_listener_id ON public.workload_document(listener_id);

CREATE TABLE IF NOT EXISTS public.workload_schedule_entry
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workload_document_id BIGINT NOT NULL,
    lesson_number INTEGER NOT NULL,
    module_number INTEGER NULL,
    module_name VARCHAR(500) NULL,
    topic TEXT NOT NULL,
    lesson_date DATE NULL,
    day_of_week VARCHAR(50) NULL,
    start_time TIME WITHOUT TIME ZONE NULL,
    end_time TIME WITHOUT TIME ZONE NULL,
    hours INTEGER NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_workload_schedule_entry_document FOREIGN KEY (workload_document_id) REFERENCES public.workload_document(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_workload_schedule_entry_document_id ON public.workload_schedule_entry(workload_document_id);

CREATE TABLE IF NOT EXISTS public.holiday_calendar_day
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE NOT NULL,
    holiday_name VARCHAR(255) NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_holiday_calendar_day_holiday_date
    ON public.holiday_calendar_day(holiday_date);
